# Site settings
title: SR Counselling
email: contact@srcounselling.in
url: https://www.srcounselling.com
description: "SR Counselling is a community of people who have come together to help people self-prepare for GRE. We have partnered with MAGOOSH to be able to provide you the best self-study resource at affordable prices. We are funded by a group of successful businessmen and entrepreneurs who want to give something back to the society by investing in YOU and your education."
keywords: "GRE, Magoosh, Account"
skills: "GRE - YOU - MAGOOSH - A Perfect Story"
meta_author: Smith James

# 404 Page
permalink: /404.html

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: SR Counselling
  location: Send us a Message
  social: Around the Web
  credits: Disclaimer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: www.srcounselling.in
  - title: facebook-f
    url: www.srcounselling.in
  - title: reddit-alien
    url: www.srcounselling.in
  - title: whatsapp
    url: www.srcounselling.in
  #- title: github
   # url: www.srcounselling.com

# Postal address (add as many lines as necessary)
address:
  - line: contact@srcounselling.in
  - line: Whatsapp- +1(570)409-7768

# Credits content
credits: 'GRE® are registered trademarks of Educational Testing Service (ETS). This website is not endorsed or approved by ETS. Magoosh Accounts are sole property of Magoosh Inc (Magoosh). This website is not endorsed or approved by Magoosh. '

# Build settings
markdown: kramdown
permalink: pretty
